# Generated by Django 5.1.4 on 2025-01-27 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0002_alter_teacher_birthday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='phone_number',
            field=models.CharField(help_text='※ハイフンあり', max_length=20, unique=True, verbose_name='電話番号'),
        ),
    ]
