# Generated by Django 5.1.4 on 2025-01-20 12:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('grades', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='title/試験名', max_length=20, verbose_name='試験名')),
                ('student_number', models.CharField(max_length=20, verbose_name='学生番号')),
                ('student_name', models.CharField(help_text='name/名前', max_length=20, verbose_name='名前')),
                ('japanese_score', models.DecimalField(decimal_places=2, help_text='score/国語の点数', max_digits=5, verbose_name='国語の点数')),
                ('math_score', models.DecimalField(decimal_places=2, help_text='score/数学の点数', max_digits=5, verbose_name='数学の点数')),
                ('english_score', models.DecimalField(decimal_places=2, help_text='score/英語の点数', max_digits=5, verbose_name='英語の点数')),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='score', to='grades.grade', verbose_name='クラス')),
            ],
            options={
                'verbose_name': '成績情報',
                'verbose_name_plural': '成績情報',
                'db_table': 'score',
            },
        ),
    ]
