# Generated by Django 5.1.4 on 2025-01-27 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parents', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='parent',
            options={'verbose_name': '保護者情報', 'verbose_name_plural': '保護者情報'},
        ),
        migrations.AlterModelTable(
            name='parent',
            table='parent',
        ),
    ]
