# Generated by Django 5.1.4 on 2025-01-27 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parents', '0002_alter_parent_options_alter_parent_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parent',
            name='phone_number',
            field=models.CharField(max_length=20, unique=True, verbose_name='電話番号'),
        ),
    ]
