# Generated by Django 5.1.4 on 2024-12-20 13:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('grades', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_number', models.CharField(max_length=20, unique=True, verbose_name='学籍番号')),
                ('student_name', models.CharField(max_length=50, verbose_name='名前')),
                ('gender', models.CharField(choices=[('M', '男性'), ('F', '女性')], max_length=1, verbose_name='性別')),
                ('birthday', models.DateField(help_text='例:2001-06-29', verbose_name='生年月日')),
                ('contact_number', models.CharField(max_length=20, verbose_name='連絡先')),
                ('address', models.TextField(verbose_name='住所')),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='grades.grade')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '学生情報',
                'verbose_name_plural': '学生情報',
                'db_table': 'student',
            },
        ),
    ]
