# Generated by Django 5.1.4 on 2025-01-20 12:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='birthday',
            field=models.DateField(help_text='例：2001-06-29', verbose_name='生年月日'),
        ),
        migrations.AlterField(
            model_name='student',
            name='contact_number',
            field=models.CharField(help_text='※ハイフンあり', max_length=20, verbose_name='連絡先'),
        ),
        migrations.AlterField(
            model_name='student',
            name='grade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='grades.grade', verbose_name='クラス'),
        ),
    ]
