# Generated by Django 5.1.4 on 2024-12-16 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade_name', models.CharField(max_length=50, unique=True, verbose_name='クラス名')),
                ('grade_number', models.CharField(max_length=10, unique=True, verbose_name='クラス番号')),
            ],
            options={
                'verbose_name': 'クラス',
                'verbose_name_plural': 'クラス名',
                'db_table': 'grade',
            },
        ),
    ]
